name: bot-test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.11'
      - name: create env file
        run: | 
          touch .env
          echo TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }} >> .env
          echo WEATHER_API_KEY=${{ secrets.WEATHER_API_KEY }} >> .env
          echo GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }} >> .env
      - name: build
        run: | 
          npm install
          npm run build
          npm run start:prod
